### ISSUE TITLE
Feature Request: Usage as a library

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/ifctool#10]
I imagine two ways to use the tool:
- As a CLI
- As a library

When using as a library, one could pass in input & output streams instead of file handles. Other parameters would stay the same.

I assume it would be pragmatic to keep both in the same repo.

Btw: For the acoustic rating app we currently went the other way around: We have the UI and service, we have the TS library with the calculation, but we do not have the CLI yet that exposes the library to the console. I imagine that all the vyzn apps will have UI, service, library, CLI.

**Comment by pablo-mayrgundter** [comment]
This is now available:

  https://www.npmjs.com/package/@bldrs-ai/ifclib

and a sample of how to use it is in this repo's web folder and live on GHP:

  https://bldrs-ai.github.io/ifctool

Also fyi @MarkusSteinbrecher 

Cheers,
Pablo
