### ISSUE TITLE
Web-ifc line at the beginning ouf the output

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/ifctool#8]
**Steps to reproduce:**

Download the [sample ifc](https://github.com/vyzn-tech/vyzn-pub/blob/main/modelstore/SEESTRASSE.ifc).

Run:
`
node src/main.js SEESTRASSE.ifc > seestrasse.json`

**Expected result:**

seestrasse.json is a valid json file.

**Actual result:**

There is an additional line at the beginning of the output.

```
web-ifc: 0.0.34 threading: 0
```

**Comment by pablo-mayrgundter** [comment]
Fixed by #13 .

**Comment by Adrian62D** [comment]
Nice, thank you, I'll test it soon.
